// <auto-generated />
using System;
using System.Collections.Generic;
using Importer.FasterKv;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Importer.FasterKv.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240408154524_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Importer.FasterKv.MotorEntry", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Fields")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<Dictionary<string, string>>("Relations")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.HasKey("Key");

                    b.ToTable("MotorEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
