version: "3.3"
services: 
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom-config.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000