<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>12</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.1" />
      <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.0-rc.2.23480.2" />
      <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />
      <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.3.2" />
      <PackageReference Include="Microsoft.Orleans.Sdk" Version="7.2.2" />
      <PackageReference Include="MongoDB.Bson" Version="2.22.0" />
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
      <PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
      <PackageReference Include="System.Text.Json" Version="8.0.5" />
      <PackageReference Include="U8XmlParser" Version="1.6.1" />
    </ItemGroup>

</Project>
