<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Importer.Zip\Importer.Zip.csproj" />
      <ProjectReference Include="..\Importer\Importer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="perf.data" />
    </ItemGroup>

</Project>
