<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Importer.Zip\Importer.Zip.csproj" />
      <ProjectReference Include="..\Importer\Importer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="perf.data" />
    </ItemGroup>

</Project>
